fix: Correct nativeImage and webContents types
Fixes errors like

app/renderer/js/tray.ts:118:22 - error TS2576: Property
'createFromBuffer' does not exist on type 'NativeImage'. Did you mean
to access the static member 'NativeImage.createFromBuffer' instead?

118   return nativeImage.createFromBuffer(pngData, {
                         ~~~~~~~~~~~~~~~~

Signed-off-by: Anders Kaseorg <andersk@mit.edu>