fix: Exclude dist in tsconfig.json
To prevent errors like this when running tsc twice:

error TS5055: Cannot write file
'/home/anders/electron/remote/dist/src/common/get-electron-binding.d.ts'
because it would overwrite input file.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>